badges:
  baseUrl: 'https://members.scouts.org.uk'
  sections:
    - name: 'Cubs'
      badgeTypes:
        - name: 'Challenge'
          url: '/supportresources/search/?cat=12,67,778'
        - name: 'Activity'
          url: '/supportresources/search/?cat=12,67,776'
        - name: 'Staged Activity'
          url: '/supportresources/search/?cat=12,67,777'